#!/usr/bin/env python3
"""
Generic video trimming based on text marker detection (OCR).

Supports multiple marker types:
- FPS counters (numeric patterns)
- Text markers (e.g., "PROGRESSO", loading text)
- Custom regex patterns

Can load ROI configuration from YAML files generated by roi_selector.py.

Usage:
    # Using YAML config file
    python src/trim/trim_by_marker.py \
        --video recordings/forza_extreme/1080p_dlaa_run1.mp4 \
        --roi-config recordings/forza_extreme/roi_trim_coordinates.yaml \
        --output recordings/forza_extreme/trimmed/1080p_dlaa_run1.mp4

    # Using manual ROI specification
    python src/trim/trim_by_marker.py \
        --video recordings/cyberpunk/1080p_dlaa_run1.mp4 \
        --roi "top-left 10%" \
        --marker-type fps \
        --output recordings/cyberpunk/trimmed/1080p_dlaa_run1.mp4
"""

import argparse
import sys
import cv2
import yaml
import re
from pathlib import Path
from typing import Optional, Tuple
import subprocess

# Import FPS OCR extractor
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))
from src.extraction.fps_ocr import FPSOCRExtractor


def load_roi_config(yaml_path: str) -> dict:
    """Load ROI configuration from YAML file."""
    with open(yaml_path, 'r') as f:
        config = yaml.safe_load(f)
    return config


def parse_roi(roi_str: str, frame_width: int = None, frame_height: int = None) -> Tuple[int, int, int, int]:
    """
    Parse ROI from string - supports pixels or percentages.

    Formats:
        - Pixels: "5,5,80,25" (x,y,width,height in pixels)
        - Percentage: "top-left 15%" (15% of screen from top-left corner)
        - Percentage: "top-right 10%" (10% of screen from top-right corner)

    Args:
        roi_str: ROI specification
        frame_width: Video width (required for percentage mode)
        frame_height: Video height (required for percentage mode)

    Returns:
        (x, y, width, height) in pixels
    """
    roi_str = roi_str.strip().lower()

    # Check if percentage format
    if '%' in roi_str:
        if frame_width is None or frame_height is None:
            raise ValueError("Frame dimensions required for percentage ROI")

        # Parse "top-left 15%" or "top-right 10%", etc.
        parts = roi_str.replace('%', '').split()
        if len(parts) != 2:
            raise ValueError(f"Percentage ROI must be 'position percent%', got: {roi_str}")

        position = parts[0]
        percent = float(parts[1]) / 100.0

        # Calculate ROI size based on percentage
        roi_w = int(frame_width * percent)
        roi_h = int(frame_height * percent)

        # Calculate position
        if position == "top-left":
            x, y = 0, 0
        elif position == "top-right":
            x, y = frame_width - roi_w, 0
        elif position == "bottom-left":
            x, y = 0, frame_height - roi_h
        elif position == "bottom-right":
            x, y = frame_width - roi_w, frame_height - roi_h
        else:
            raise ValueError(f"Unknown position: {position}. Use top-left, top-right, bottom-left, or bottom-right")

        return (x, y, roi_w, roi_h)

    # Pixel format: "x,y,width,height"
    parts = roi_str.split(',')
    if len(parts) != 4:
        raise ValueError(f"Pixel ROI must be 'x,y,width,height', got: {roi_str}")
    return tuple(map(int, parts))


def detect_marker_with_fps_extractor(roi_crop, extractor, marker_type: str, regex_pattern: str = None, debug: bool = False) -> bool:
    """
    Detect marker in ROI crop using FPS OCR extractor.

    Args:
        roi_crop: Cropped frame region
        extractor: FPSOCRExtractor instance
        marker_type: "fps", "text", or "regex"
        regex_pattern: Pattern to match (for text/regex types)
        debug: If True, print OCR results

    Returns:
        True if marker detected, False otherwise
    """
    if marker_type == "fps":
        # Use existing FPS detection logic
        fps_value = extractor.read_fps_from_roi(roi_crop)
        if debug and fps_value is not None:
            print(f"    [DEBUG] FPS detected: {fps_value:.1f}")
        return fps_value is not None and fps_value > 0

    # For text/regex, we need to get raw OCR text
    # Using EasyOCR directly
    if not hasattr(extractor, 'reader'):
        return False

    results = extractor.reader.readtext(roi_crop, detail=1)
    if not results:
        if debug:
            print(f"    [DEBUG] No OCR results")
        return False

    # Extract text with confidence > 0.3
    detected_texts = [text for (_, text, conf) in results if conf > 0.3]
    combined_text = ' '.join(detected_texts)

    if debug:
        print(f"    [DEBUG] OCR text: '{combined_text}'")

    if marker_type == "text":
        # Exact text match (case insensitive)
        return regex_pattern.lower() in combined_text.lower()
    elif marker_type == "regex":
        # Regex pattern match
        return re.search(regex_pattern, combined_text, re.IGNORECASE) is not None

    return False


def detect_marker_range(video_path: str, roi: Tuple[int, int, int, int],
                        marker_type: str, regex_pattern: str = None,
                        window_size: int = 30, debug: bool = False) -> Optional[Tuple[int, int]]:
    """
    Detect frame range where marker is visible using sliding window OCR.

    Uses a sliding window approach to batch process frames efficiently:
    - Loads frames in windows of `window_size` frames
    - Processes entire window with OCR model (keeps model in memory)
    - Finds first and last frame where marker is detected

    Args:
        video_path: Path to video file
        roi: (x, y, width, height) for marker location
        marker_type: "fps", "text", or "regex"
        regex_pattern: Pattern to match (for text/regex types)
        window_size: Number of frames to process in each batch (default: 30)

    Returns:
        (first_frame, last_frame) or None if marker never detected
    """
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open video: {video_path}")

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS)

    print(f"Video: {total_frames} frames @ {fps:.2f} FPS")
    print(f"Scanning for marker (type: {marker_type}) in ROI: x={roi[0]}, y={roi[1]}, w={roi[2]}, h={roi[3]}")
    if regex_pattern:
        print(f"Pattern: {regex_pattern}")
    print(f"Using sliding window size: {window_size} frames")

    # Initialize OCR extractor (loaded once, reused for all frames)
    extractor = FPSOCRExtractor(roi=roi, use_easyocr=True)

    x, y, w, h = roi

    # Debug: Save first frame ROI crop for verification
    if debug:
        cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
        ret, test_frame = cap.read()
        if ret:
            test_crop = test_frame[y:y+h, x:x+w]
            debug_path = Path(video_path).parent / "debug_roi_crop.png"
            cv2.imwrite(str(debug_path), test_crop)
            print(f"[DEBUG] Saved ROI crop from first frame to: {debug_path}")
            print(f"[DEBUG] ROI coordinates: x={x}, y={y}, w={w}, h={h}")
            print(f"[DEBUG] Crop size: {test_crop.shape}")
        cap.set(cv2.CAP_PROP_POS_FRAMES, 0)  # Reset to start

    # Scan forward to find FIRST frame with marker using sliding window
    print("\n[1/2] Scanning forward with sliding window (every frame)...")
    first_frame = None

    from tqdm import tqdm

    frame_idx = 0
    with tqdm(total=total_frames, desc="Scanning forward", unit="frame") as pbar:
        while frame_idx < total_frames:
            # Read window of frames
            window_frames = []
            window_indices = []

            for i in range(window_size):
                ret, frame = cap.read()
                if not ret:
                    break
                window_frames.append(frame)
                window_indices.append(frame_idx + i)

            if not window_frames:
                break

            # Process entire window with OCR (model stays in memory)
            for i, (frame, idx) in enumerate(zip(window_frames, window_indices)):
                # Extract ROI
                roi_crop = frame[y:y+h, x:x+w]

                # Detect marker
                detected = detect_marker_with_fps_extractor(roi_crop, extractor, marker_type, regex_pattern, debug)

                if detected:
                    first_frame = idx
                    print(f"\n  ✓ First marker detection at frame {first_frame} (t={first_frame/fps:.2f}s)")
                    break

            pbar.update(len(window_frames))
            frame_idx += len(window_frames)

            if first_frame is not None:
                break

    if first_frame is None:
        print("\n  ✗ Marker never detected in video")
        cap.release()
        return None

    # Scan backward to find LAST frame with marker using sliding window
    print(f"\n[2/2] Scanning backward with sliding window (every frame)...")
    last_frame = None

    # Start from end, move backward in windows
    frame_idx = total_frames - 1
    with tqdm(total=(total_frames - first_frame), desc="Scanning backward", unit="frame") as pbar:
        while frame_idx >= first_frame:
            # Calculate window start (move backward)
            window_start = max(first_frame, frame_idx - window_size + 1)
            window_end = frame_idx

            # Read window of frames backward
            window_frames = []
            window_indices = []

            for idx in range(window_end, window_start - 1, -1):
                cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
                ret, frame = cap.read()
                if not ret:
                    continue
                window_frames.append(frame)
                window_indices.append(idx)

            if not window_frames:
                break

            # Process entire window with OCR (model stays in memory)
            for frame, idx in zip(window_frames, window_indices):
                # Extract ROI
                roi_crop = frame[y:y+h, x:x+w]

                # Detect marker
                detected = detect_marker_with_fps_extractor(roi_crop, extractor, marker_type, regex_pattern)

                if detected:
                    last_frame = idx
                    print(f"\n  ✓ Last marker detection at frame {last_frame} (t={last_frame/fps:.2f}s)")
                    break

            pbar.update(len(window_frames))
            frame_idx = window_start - 1

            if last_frame is not None:
                break

    if last_frame is None:
        print(f"  ✗ Marker disappeared after frame {first_frame}, using end of video")
        last_frame = total_frames - 1

    cap.release()

    print(f"\n{'='*80}")
    print(f"Marker Range Detected".center(80))
    print(f"{'='*80}")
    print(f"First frame: {first_frame} (t={first_frame/fps:.2f}s)")
    print(f"Last frame:  {last_frame} (t={last_frame/fps:.2f}s)")
    print(f"Duration:    {(last_frame - first_frame)/fps:.2f}s ({last_frame - first_frame} frames)")

    return first_frame, last_frame


def trim_video(input_path: str, output_path: str,
               first_frame: int, last_frame: int):
    """
    Trim video using FFmpeg with frame-accurate seeking.

    Args:
        input_path: Source video
        output_path: Output trimmed video
        first_frame: First frame to include
        last_frame: Last frame to include
    """
    # Get video FPS
    cap = cv2.VideoCapture(input_path)
    fps = cap.get(cv2.CAP_PROP_FPS)
    cap.release()

    # Convert frames to timestamps
    start_time = first_frame / fps
    duration = (last_frame - first_frame) / fps

    print(f"\nTrimming video with FFmpeg...")
    print(f"  Start: {start_time:.3f}s (frame {first_frame})")
    print(f"  Duration: {duration:.3f}s ({last_frame - first_frame} frames)")

    # Create output directory
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    # FFmpeg command for frame-accurate trimming
    cmd = [
        'ffmpeg',
        '-y',  # Overwrite output
        '-ss', str(start_time),  # Seek to start
        '-i', input_path,
        '-t', str(duration),  # Duration
        '-c:v', 'libx264',  # Re-encode to ensure frame accuracy
        '-crf', '18',  # High quality
        '-preset', 'fast',
        '-c:a', 'aac',
        '-b:a', '128k',
        output_path
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"✗ FFmpeg failed:")
        print(result.stderr)
        sys.exit(1)

    # Verify output
    cap_out = cv2.VideoCapture(output_path)
    output_frames = int(cap_out.get(cv2.CAP_PROP_FRAME_COUNT))
    cap_out.release()

    print(f"  ✓ Trimmed video saved: {output_path}")
    print(f"  Output: {output_frames} frames")


def main():
    parser = argparse.ArgumentParser(
        description='Generic video trimming based on text marker detection',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Using YAML ROI config
  python src/trim/trim_by_marker.py \\
      --video recordings/forza_extreme/1080p_dlaa_run1.mp4 \\
      --roi-config recordings/forza_extreme/roi_trim_coordinates.yaml \\
      --output recordings/forza_extreme/trimmed/1080p_dlaa_run1.mp4

  # Manual ROI and FPS marker
  python src/trim/trim_by_marker.py \\
      --video recordings/cyberpunk/1080p_dlaa_run1.mp4 \\
      --roi "top-left 10%" \\
      --marker-type fps \\
      --output recordings/cyberpunk/trimmed/1080p_dlaa_run1.mp4

  # Manual ROI and text marker
  python src/trim/trim_by_marker.py \\
      --video recordings/forza_extreme/1080p_dlaa_run1.mp4 \\
      --roi "0,0,250,80" \\
      --marker-type text \\
      --marker-pattern "PROGRESSO" \\
      --output recordings/forza_extreme/trimmed/1080p_dlaa_run1.mp4
        """
    )
    parser.add_argument('--video', required=True,
                       help='Input video path')
    parser.add_argument('--output', required=True,
                       help='Output trimmed video path')
    parser.add_argument('--roi-config', type=str,
                       help='Path to YAML ROI config file (generated by roi_selector.py)')
    parser.add_argument('--roi', type=str,
                       help='Manual ROI as "x,y,width,height" (pixels) or "top-left 15%%" (percentage)')
    parser.add_argument('--marker-type', type=str, choices=['fps', 'text', 'regex'],
                       help='Marker type (required if not using --roi-config)')
    parser.add_argument('--marker-pattern', type=str,
                       help='Pattern to match (required for text/regex types)')
    parser.add_argument('--dry-run', action='store_true',
                       help='Only detect range, do not trim')
    parser.add_argument('--debug', action='store_true',
                       help='Print OCR detection results for debugging')

    args = parser.parse_args()

    # Load configuration
    roi = None
    marker_type = None
    marker_pattern = None

    if args.roi_config:
        # Load from YAML config
        print(f"Loading ROI config from: {args.roi_config}")
        config = load_roi_config(args.roi_config)

        # Extract ROI pixels
        roi_str = config['roi']['pixels']
        roi = parse_roi(roi_str)

        # Get reference resolution from config
        ref_resolution = config['video_info']['resolution']
        ref_width, ref_height = map(int, ref_resolution.split('x'))

        # Get current video resolution
        cap = cv2.VideoCapture(args.video)
        curr_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        curr_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        cap.release()

        # Scale ROI if resolutions differ
        if curr_width != ref_width or curr_height != ref_height:
            x, y, w, h = roi
            scale_x = curr_width / ref_width
            scale_y = curr_height / ref_height

            roi = (
                int(x * scale_x),
                int(y * scale_y),
                int(w * scale_x),
                int(h * scale_y)
            )
            print(f"  Reference resolution: {ref_width}x{ref_height}")
            print(f"  Current resolution: {curr_width}x{curr_height}")
            print(f"  Scaled ROI: {roi_str} -> {roi[0]},{roi[1]},{roi[2]},{roi[3]}")
        else:
            print(f"  ROI: {roi}")

        # Extract marker info
        marker_type = config['marker']['type']
        marker_pattern = config['marker']['regex']
        print(f"  Marker type: {marker_type}")
        print(f"  Marker pattern: {marker_pattern}")

    else:
        # Use manual specification
        if not args.roi or not args.marker_type:
            print("✗ Error: Either --roi-config OR (--roi AND --marker-type) is required")
            sys.exit(1)

        # Parse manual ROI
        if '%' in args.roi:
            cap = cv2.VideoCapture(args.video)
            frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            cap.release()
            roi = parse_roi(args.roi, frame_width, frame_height)
            print(f"Using percentage ROI: {args.roi} -> {roi}")
        else:
            roi = parse_roi(args.roi)
            print(f"Using manual ROI: {roi}")

        marker_type = args.marker_type
        marker_pattern = args.marker_pattern

        if marker_type in ['text', 'regex'] and not marker_pattern:
            print(f"✗ Error: --marker-pattern is required for marker type '{marker_type}'")
            sys.exit(1)

    # Detect marker range
    marker_range = detect_marker_range(args.video, roi, marker_type, marker_pattern, debug=args.debug)

    if marker_range is None:
        print("\n✗ Marker never detected in video. Cannot trim.")
        sys.exit(1)

    first_frame, last_frame = marker_range

    # Trim video (unless dry-run)
    if args.dry_run:
        print("\n[Dry run] Skipping actual trim")
        print(f"Would trim: {args.video} -> {args.output}")
        print(f"Range: frames {first_frame}-{last_frame}")
    else:
        trim_video(args.video, args.output, first_frame, last_frame)
        print("\n✓ Video trimming complete")


if __name__ == '__main__':
    main()
